name: Node.js CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [11.3, 11.x, 12.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Use Node.JS v11.3
      uses: actions/setup-node@v1
      with:
        node-version: 11.3
    - run: |
      npm install
      make test-coverage
    - run: npm run build
    - run: npm run test
    - name: Run Code Coverage (via coveralls.io)
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    # - run: npm run coveralls
    - run: npm run lint
      env:
        CI: true
