name: Node.js CI


on: pull_request

jobs:
  lint-diff:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - run: git log
    - run: git log HEAD
    - run: git log HEAD~1
    - name: Use Node.JS v11.3
      uses: actions/setup-node@v1
      with:
        node-version: 11.3
    - run: npm install
    - run: npm run lint-diff HEAD~1..HEAD
    - name: Check test coverage versus target branch (via coveralls.io)
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}