name: protected-branch-checks

on:
  push:
    branches:
      - master
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Read .nvmrc
      run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
      id: nvm

    - name: Use Node.js (.nvmrc)
      uses: actions/setup-node@v1
      with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"

    - name: Install dependencies
      run: npm install

    - name: Find lint errors on changed lines
      run: npm run lint

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Read .nvmrc
      run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
      id: nvm

    - name: Use Node.js (.nvmrc)
      uses: actions/setup-node@v1
      with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"

    - name: Install dependencies
      run: npm install

    - name: Build application
      run: npm run build

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Read .nvmrc
      run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
      id: nvm

    - name: Use Node.js (.nvmrc)
      uses: actions/setup-node@v1
      with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"

    - name: Install dependencies
      run: npm install

    - name: Run test suite
      run: npm run test

    - name: Check test coverage versus previous commit (via coveralls.io)
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
      if: ${{ always() }}
