name: Node.js CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Use Node.JS v11.3
      uses: actions/setup-node@v1
      with:
        node-version: 11.3
    - run: npm install
    # - run: npm run lint-diff ${{ github.base_ref }}..${{ github.head_ref }} --
    - run: npm run lint-diff HEAD~1..HEAD
    - run: npm run build
    - run: npm run test
    - name: Check test coverage versus last commit (via coveralls.io)
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    # - run: npm run coveralls
    # - run: npm run lint
      env:
        CI: true